# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Popcorn' do

pod 'Parse'
pod 'Facebook-iOS-SDK'
pod 'SDWebImage'

end

target 'PopcornTests' do

end

